replicaCount: 1

image:
  repository: ghcr.io/sagargi/shipflow-gitops
  tag: latest
  pullPolicy: IfNotPresent

container:
  port: 3000

service:
  type: ClusterIP
  port: 3000

env:
  NODE_ENV: production
  LOG_LEVEL: info

probes:
  liveness:
    path: /health
    initialDelaySeconds: 10
    periodSeconds: 10

  readiness:
    path: /health
    initialDelaySeconds: 5
    periodSeconds: 5

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 250m
    memory: 256Mi

# NOTE:
# These values are for local development only.
# In production, use Sealed Secrets, External Secrets,
# or another secure secret management solution.
secrets:
  JWT_SECRET: my-super-secret-key