name: CI Pipeline

on:
  push:
    branches:
      - main
    paths-ignore:
      - "helm/**"

permissions:
  contents: write
  packages: write

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install Dependencies
        run: npm ci
        working-directory: app

      - name: Run Tests
        run: npm test
        working-directory: app

      - name: Downcase repository name
        run: |
          echo "REPO_LC=${GITHUB_REPOSITORY,,}" >> $GITHUB_ENV

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v6
        with:
          context: ./app
          push: true
          tags: |
            ghcr.io/${{ env.REPO_LC }}:${{ github.sha }}
            ghcr.io/${{ env.REPO_LC }}:latest
      
      - name: Update Helm Image Tag
        run: |
          sed -i "s/^  tag:.*/  tag: ${{ github.sha }}/" helm/shipflow-api/values.yaml

      - name: Commit Updated Helm Values
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

          git add helm/shipflow-api/values.yaml

          git diff --cached --quiet && exit 0

          git commit -m "Update image tag to ${{ github.sha }}"
          git push origin HEAD:${{ github.ref_name }}